[workspace]
name = "corneto"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[dependencies]
python = "3.11.*"
pip = "*"
graphviz = "*"
python-graphviz = "*"
networkx = "*"
pandas = "*"
matplotlib = "*"

[pypi-dependencies]
sphinx = ">=5.0"
myst-parser = ">=0.18.1"
pydata-sphinx-theme = ">=0.16.1"
sphinxcontrib-napoleon = ">=0.7"
sphinxcontrib-bibtex = ">=2.5.0"
sphinx-design = ">=0.4.1"
sphinx-favicon = ">=1.0.1"
myst-nb = ">=0.17.2"
sphinx-autodoc-typehints = ">=1.21.8"
sphinx-hoverxref = ">=1.3.0"
pydot = ">=3.0.4"
pcst-fast = ">=1.0.10"
gurobipy = "*"
picos = "==2.6.2"
ipykernel = "*"
nbclient = "*"
papermill = "*"

[tasks]
setup = "python -m pip install -e ."
docs = "python -m pip install -e . && sphinx-build -b html docs docs/_build/html"
docs-force = "python -m pip install -e . && rm -rf docs/_jupyter-cache docs/_build && sphinx-build -b html -E -a -D nb_execution_mode=force docs docs/_build/html"
docs-notebooks-rewrite = "python docs/tutorials/run_notebooks.py --rewrite --editable-corneto"
docs-guide-rewrite = "python -m pip install -e . && python -m pip install --upgrade ipykernel papermill nbclient && python docs/guide/run_guide_notebooks.py --rewrite"
docs-serve = "python -m http.server 8000 --directory docs/_build/html"
